services:
    weaviate:
        command:
            - --host
            - 0.0.0.0
            - --port
            - '8080'
            - --scheme
            - http
        image: semitechnologies/weaviate:1.34.0
        ports:
            - 8080:8080
            - 50051:50051
        volumes:
            - weaviate_data:/var/lib/weaviate
        restart: on-failure:0
        environment:
            QUERY_DEFAULTS_LIMIT: 25
            AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
            PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
            CLUSTER_HOSTNAME: 'node1'
            ENABLE_MODULES: text2vec-transformers,,img2vec-neural
            TRANSFORMERS_INFERENCE_API: http://text2vec:8080
            IMAGE_INFERENCE_API: http://img2vec:8080
    text2vec:
        image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
        environment:
            ENABLE_CUDA: 0
    img2vec:
        image: semitechnologies/img2vec-pytorch:resnet50
        restart: always
        environment:
            ENABLE_CUDA: '0'
volumes:
    weaviate_data:
