from matplotlib import colors
import math

css_color_map = {
    "aliceblue": "xanh alice",
    "antiquewhite": "trắng cổ điển",
    "aqua": "xanh aqua",
    "aquamarine": "xanh ngọc bích",
    "azure": "xanh lam",
    "beige": "be",
    "bisque": "kem",
    "black": "đen",
    "blanchedalmond": "da người",
    "blue": "xanh dương",
    "blueviolet": "xanh tím",
    "brown": "nâu",
    "burlywood": "gỗ nâu nhạt",
    "cadetblue": "xanh lính",
    "chartreuse": "vàng chanh",
    "chocolate": "nâu chocolate",
    "coral": "hồng san hô",
    "cornflowerblue": "xanh bắp cải",
    "cornsilk": "vàng tơ ngô",
    "crimson": "đỏ thẫm",
    "cyan": "lam",
    "darkblue": "xanh dương đậm",
    "darkcyan": "lam đậm",
    "darkgoldenrod": "vàng đậm",
    "darkgray": "xám đậm",
    "darkgreen": "xanh lá đậm",
    "darkgrey": "xám đậm",
    "darkkhaki": "vàng ô liu đậm",
    "darkmagenta": "đỏ tía đậm",
    "darkolivegreen": "xanh ô liu đậm",
    "darkorange": "cam đậm",
    "darkorchid": "tím lan đậm",
    "darkred": "đỏ đậm",
    "darksalmon": "cá hồi đậm",
    "darkseagreen": "xanh biển đậm",
    "darkslateblue": "xanh than đậm",
    "darkslategray": "xám than đậm",
    "darkslategrey": "xám than đậm",
    "darkturquoise": "ngọc lam đậm",
    "darkviolet": "tím violet đậm",
    "deeppink": "hồng đậm",
    "deepskyblue": "xanh trời đậm",
    "dimgray": "xám mờ",
    "dimgrey": "xám mờ",
    "dodgerblue": "xanh dương sáng",
    "firebrick": "gạch đỏ",
    "floralwhite": "trắng hoa",
    "forestgreen": "xanh rừng",
    "fuchsia": "đỏ tía",
    "gainsboro": "xám sáng",
    "ghostwhite": "trắng ma",
    "gold": "vàng",
    "goldenrod": "vàng cỏ",
    "gray": "xám",
    "green": "xanh lá",
    "greenyellow": "xanh lá vàng",
    "grey": "xám",
    "honeydew": "mật ong",
    "hotpink": "hồng nóng",
    "indianred": "đỏ Ấn Độ",
    "indigo": "chàm",
    "ivory": "ngà voi",
    "khaki": "kaki",
    "lavender": "hoa oải hương",
    "lavenderblush": "hồng oải hương",
    "lawngreen": "xanh cỏ",
    "lemonchiffon": "chanh nhạt",
    "lightblue": "xanh dương nhạt",
    "lightcoral": "hồng san hô nhạt",
    "lightcyan": "xanh lam nhạt",
    "lightgoldenrodyellow": "vàng nhạt",
    "lightgray": "xám nhạt",
    "lightgreen": "xanh lá nhạt",
    "lightgrey": "xám nhạt",
    "lightpink": "hồng nhạt",
    "lightsalmon": "cam cá hồi nhạt",
    "lightseagreen": "xanh biển nhạt",
    "lightskyblue": "xanh trời nhạt",
    "lightslategray": "xám than nhạt",
    "lightslategrey": "xám than nhạt",
    "lightsteelblue": "xanh thép nhạt",
    "lightyellow": "vàng nhạt",
    "lime": "xanh chanh",
    "limegreen": "xanh lá chanh",
    "linen": "da người linen",
    "magenta": "đỏ tía",
    "maroon": "đỏ nâu",
    "mediumaquamarine": "ngọc bích vừa",
    "mediumblue": "xanh dương vừa",
    "mediumorchid": "tím lan vừa",
    "mediumpurple": "tím vừa",
    "mediumseagreen": "xanh biển vừa",
    "mediumslateblue": "xanh than vừa",
    "mediumspringgreen": "xanh xuân vừa",
    "mediumturquoise": "ngọc lam vừa",
    "mediumvioletred": "đỏ tía vừa",
    "midnightblue": "xanh dương đêm",
    "mintcream": "kem bạc hà",
    "mistyrose": "hồng sương mù",
    "moccasin": "da người moccasin",
    "navajowhite": "trắng navajo",
    "navy": "hải quân",
    "oldlace": "trắng oldlace",
    "olive": "ô liu",
    "olivedrab": "ô liu xỉn",
    "orange": "cam",
    "orangered": "cam đỏ",
    "orchid": "tím hoa lan",
    "palegoldenrod": "vàng nhạt",
    "palegreen": "xanh lá nhạt",
    "paleturquoise": "ngọc lam nhạt",
    "palevioletred": "đỏ tía nhạt",
    "papayawhip": "trắng papaya",
    "peachpuff": "đào nhạt",
    "peru": "nâu peru",
    "pink": "hồng",
    "plum": "mận",
    "powderblue": "xanh bột",
    "purple": "tím",
    "rebeccapurple": "tím rebecca",
    "red": "đỏ",
    "rosybrown": "nâu hồng",
    "royalblue": "xanh hoàng gia",
    "saddlebrown": "nâu yên ngựa",
    "salmon": "cam cá hồi",
    "sandybrown": "nâu cát",
    "seagreen": "xanh biển",
    "seashell": "trắng vỏ sò",
    "sienna": "nâu đất",
    "silver": "bạc",
    "skyblue": "xanh trời",
    "slateblue": "xanh than",
    "slategray": "xám than",
    "slategrey": "xám than",
    "snow": "trắng tuyết",
    "springgreen": "xanh xuân",
    "steelblue": "xanh thép",
    "tan": "nâu nhạt",
    "teal": "xanh lam",
    "thistle": "tím thistle",
    "tomato": "đỏ cà chua",
    "turquoise": "xanh ngọc lam",
    "violet": "tím violet",
    "wheat": "trắng ngà lúa mì",
    "white": "trắng",
    "whitesmoke": "trắng khói",
    "yellow": "vàng",
    "yellowgreen": "xanh lá mạ",
}


def hex_to_rgb(hex_color):
    hex_color = hex_color.strip().lstrip('#')
    return tuple(int(hex_color[i : i + 2], 16) for i in (0, 2, 4))


def closest_color_name(hex_color):
    input_rgb = hex_to_rgb(hex_color)
    min_dist = float('inf')
    closest_name = None

    for name, hex_val in colors.CSS4_COLORS.items():
        css_rgb = hex_to_rgb(hex_val)
        dist = math.sqrt(sum((a - b) ** 2 for a, b in zip(input_rgb, css_rgb)))
        if dist < min_dist:
            min_dist = dist
            closest_name = name

    return css_color_map.get(closest_name, closest_name)
